apiVersion: v1
kind: Secret
metadata:
  name: animeenigma-secrets
type: Opaque
stringData:
  # IMPORTANT: Replace these in production!
  jwt-secret: "change-this-in-production"
  stream-token-secret: "change-this-in-production"
  db-password: "postgres"
  redis-password: ""
  minio-access-key: "minioadmin"
  minio-secret-key: "minioadmin"
