apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: monitoring
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "AnimeEnigma Production",
          "Group": "Servers",
          "Host": "postgres.animeenigma.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "animeenigma",
          "Username": "animeenigma",
          "SSLMode": "prefer"
        }
      }
    }
